export const flt_content = [
    { code: '1', zhInfo: '充电总压过压', enInfo: 'Chg Pack OV' },
    { code: '2', zhInfo: '充电总压欠压', enInfo: 'Chg Pack UV' },
    { code: '3', zhInfo: '充电单体过压', enInfo: 'Chg Cell OV' },
    { code: '4', zhInfo: '充电单体欠压', enInfo: 'Chg Cell UV' },
    { code: '5', zhInfo: '充电单体压差', enInfo: 'Chg Cell Diff' },
    { code: '6', zhInfo: '充电过温', enInfo: 'Chg OT' },
    { code: '7', zhInfo: '充电低温', enInfo: 'Chg UT' },
    { code: '8', zhInfo: '充电温差过大', enInfo: ' Chg Temp Diff' },
    { code: '9', zhInfo: '充电过流', enInfo: 'Chg OC' },
    { code: '10', zhInfo: '放电总压过压', enInfo: ' Dsg Pack OV' },
    { code: '11', zhInfo: '放电总压欠压', enInfo: ' Dsg Pack UV' },
    { code: '12', zhInfo: '放电单体过压', enInfo: ' Dsg Cell OV' },
    { code: '13', zhInfo: '放电单体欠压', enInfo: ' Dsg Cell UV' },
    { code: '14', zhInfo: '放电单体压差', enInfo: ' Dsg Cell Diff' },
    { code: '15', zhInfo: '放电过温', enInfo: 'Dsg OT' },
    { code: '16', zhInfo: '放电低温', enInfo: 'Dsg UT' },
    { code: '17', zhInfo: '放电温差过大', enInfo: ' Dsg Temp Diff' },
    { code: '18', zhInfo: '放电过流', enInfo: ' Dsg OC' },
    { code: '19', zhInfo: 'SOC低', enInfo: 'SOC Low' },
    { code: '20', zhInfo: '绝缘', enInfo: 'Insulation' },
    { code: '21', zhInfo: '回馈过流', enInfo: ' Feed OC' },
    { code: '22', zhInfo: 'SOC高', enInfo: 'SOC High' },
    { code: '23', zhInfo: '保留', enInfo: 'Retain' },
    { code: '24', zhInfo: '保留', enInfo: 'Retain' },
    { code: '25', zhInfo: '保留', enInfo: 'Retain' },
    { code: '26', zhInfo: '保留', enInfo: 'Retain' },
    { code: '27', zhInfo: '保留', enInfo: 'Retain' },
    { code: '28', zhInfo: '预充故障', enInfo: ' PreChg' },
    { code: '29', zhInfo: '粘连故障', enInfo: ' Adhesion' },
    { code: '30', zhInfo: '充电插座过温', enInfo: 'ChgCnctOT' },
    { code: '31', zhInfo: '放电继电器过温', enInfo: ' DsgCnctOT' },
    { code: '32', zhInfo: '充电继电器过温', enInfo: ' ChgRlyOT' },
    { code: '33', zhInfo: '危险值过压', enInfo: '  Danger OV' },
    { code: '34', zhInfo: '危险值欠压', enInfo: '  Danger UV' },
    { code: '35', zhInfo: '危险值过温', enInfo: '  Danger OT' },
    { code: '36', zhInfo: '通信故障', enInfo: ' Commu.' },
    { code: '37', zhInfo: '系统故障', enInfo: ' Sys Err' },
    { code: '38', zhInfo: '危险值低温', enInfo: '  Danger UT' },
    { code: '39', zhInfo: '电压采集故障', enInfo: '  Cell Smpl Err' },
    { code: '40', zhInfo: '温度采集故障', enInfo: '  Temp Smpl Err' },
    { code: '41', zhInfo: '自检故障', enInfo: 'SelfChkErr' },
    { code: '42', zhInfo: '热失控', enInfo: 'ThermalRunaway' },
    { code: '43', zhInfo: '自定义1', enInfo: 'UserDef1' },
    { code: '44', zhInfo: '自定义2', enInfo: 'UserDef2' },
]